/* eslint-disable */

export const event = 'pull_request_review'
export const approved = JSON.stringify({
	"action": "submitted",
	"review": {
		"id": 2626884,
		"user": {
			"login": "baxterthehacker",
			"id": 6752317,
		},
		"body": "Looks great!",
		"submitted_at": "2016-10-03T23:39:09Z",
		"state": "approved",
		"html_url": "https://github.com/baxterthehacker/public-repo/pull/8#pullrequestreview-2626884",
		"pull_request_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/8",
	},
	"pull_request": {
		"url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/8",
		"issue_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/8",
		"id": 87811438,
		"number": 8,
		"state": "open",
		"locked": false,
		"title": "Add a README description",
		"user": {
			"login": "Kyle-Mendes",
			"id": 6400039,
			"avatar_url": "https://avatars.githubusercontent.com/u/2546?v=3",
			"gravatar_id": "",
			"url": "https://api.github.com/users/skalnik",
			"type": "User",
			"site_admin": true
		},
		"body": "Just a few more details",
		"created_at": "2016-10-03T23:37:43Z",
		"updated_at": "2016-10-03T23:39:09Z",
		"closed_at": null,
		"merged_at": null,
		"merge_commit_sha": "faea154a7decef6819754aab0f8c0e232e6c8b4f",
		"assignee": null,
		"assignees": [],
		"milestone": null,
		"head": {
			"label": "skalnik:patch-2",
			"ref": "patch-2",
			"sha": "b7a1f9c27caa4e03c14a88feb56e2d4f7500aa63",
			"user": {
				"login": "skalnik",
				"id": 2546,
				"avatar_url": "https://avatars.githubusercontent.com/u/2546?v=3",
				"gravatar_id": "",
				"url": "https://api.github.com/users/skalnik",
				"type": "User",
				"site_admin": true
			},
			"repo": {
				"id": 69919152,
				"name": "public-repo",
				"full_name": "skalnik/public-repo",
				"owner": {
					"login": "skalnik",
					"id": 2546,
					"avatar_url": "https://avatars.githubusercontent.com/u/2546?v=3",
					"gravatar_id": "",
					"type": "User",
					"site_admin": true
				},
				"private": false,
				"html_url": "https://github.com/skalnik/public-repo",
				"description": null,
				"fork": true,
				"url": "https://api.github.com/repos/skalnik/public-repo",
				"created_at": "2016-10-03T23:23:31Z",
				"updated_at": "2016-08-15T17:19:01Z",
				"pushed_at": "2016-10-03T23:36:52Z",
				"git_url": "git://github.com/skalnik/public-repo.git",
				"ssh_url": "git@github.com:skalnik/public-repo.git",
				"clone_url": "https://github.com/skalnik/public-repo.git",
				"svn_url": "https://github.com/skalnik/public-repo",
				"homepage": null,
				"size": 233,
				"stargazers_count": 0,
				"watchers_count": 0,
				"language": null,
				"has_issues": false,
				"has_downloads": true,
				"has_wiki": true,
				"has_pages": false,
				"forks_count": 0,
				"mirror_url": null,
				"open_issues_count": 0,
				"forks": 0,
				"open_issues": 0,
				"watchers": 0,
				"default_branch": "master"
			}
		},
		"base": {
			"label": "baxterthehacker:master",
			"ref": "master",
			"sha": "9049f1265b7d61be4a8904a9a27120d2064dab3b",
			"user": {
				"login": "baxterthehacker",
				"id": 6752317,
				"avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
				"gravatar_id": "",
				"url": "https://api.github.com/users/baxterthehacker",
				"type": "User",
				"site_admin": false
			},
			"repo": {
				"id": 35129377,
				"name": "public-repo",
				"full_name": "baxterthehacker/public-repo",
				"owner": {
					"login": "baxterthehacker",
					"id": 6752317,
					"avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
					"gravatar_id": "",
					"url": "https://api.github.com/users/baxterthehacker",
					"type": "User",
					"site_admin": false
				},
				"private": false,
				"html_url": "https://github.com/baxterthehacker/public-repo",
				"description": "",
				"fork": false,
				"url": "https://api.github.com/repos/baxterthehacker/public-repo",
				"created_at": "2015-05-05T23:40:12Z",
				"updated_at": "2016-08-15T17:19:01Z",
				"pushed_at": "2016-10-03T23:37:43Z",
				"git_url": "git://github.com/baxterthehacker/public-repo.git",
				"ssh_url": "git@github.com:baxterthehacker/public-repo.git",
				"clone_url": "https://github.com/baxterthehacker/public-repo.git",
				"svn_url": "https://github.com/baxterthehacker/public-repo",
				"homepage": null,
				"size": 233,
				"stargazers_count": 2,
				"watchers_count": 2,
				"language": null,
				"has_issues": true,
				"has_downloads": true,
				"has_wiki": true,
				"has_pages": true,
				"forks_count": 2,
				"mirror_url": null,
				"open_issues_count": 5,
				"forks": 2,
				"open_issues": 5,
				"watchers": 2,
				"default_branch": "master"
			}
		},
	},
})

export const denied = JSON.stringify({
	"action": "submitted",
	"review": {
		"id": 2626884,
		"user": {
			"login": "baxterthehacker",
			"id": 6752317,
		},
		"body": "Looks terrible!",
		"submitted_at": "2016-10-03T23:39:09Z",
		"state": "changes_requested",
		"html_url": "https://github.com/baxterthehacker/public-repo/pull/8#pullrequestreview-2626884",
		"pull_request_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/8",
	},
	"pull_request": {
		"url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/8",
		"issue_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/8",
		"id": 87811438,
		"number": 8,
		"state": "open",
		"locked": false,
		"title": "Add a README description",
		"user": {
			"login": "Kyle-Mendes",
			"id": 6400039,
			"avatar_url": "https://avatars.githubusercontent.com/u/2546?v=3",
			"gravatar_id": "",
			"url": "https://api.github.com/users/skalnik",
			"type": "User",
			"site_admin": true
		},
		"body": "Just a few more details",
		"created_at": "2016-10-03T23:37:43Z",
		"updated_at": "2016-10-03T23:39:09Z",
		"closed_at": null,
		"merged_at": null,
		"merge_commit_sha": "faea154a7decef6819754aab0f8c0e232e6c8b4f",
		"assignee": null,
		"assignees": [],
		"milestone": null,
		"head": {
			"label": "skalnik:patch-2",
			"ref": "patch-2",
			"sha": "b7a1f9c27caa4e03c14a88feb56e2d4f7500aa63",
			"user": {
				"login": "skalnik",
				"id": 2546,
				"avatar_url": "https://avatars.githubusercontent.com/u/2546?v=3",
				"gravatar_id": "",
				"url": "https://api.github.com/users/skalnik",
				"type": "User",
				"site_admin": true
			},
			"repo": {
				"id": 69919152,
				"name": "public-repo",
				"full_name": "skalnik/public-repo",
				"owner": {
					"login": "skalnik",
					"id": 2546,
					"avatar_url": "https://avatars.githubusercontent.com/u/2546?v=3",
					"gravatar_id": "",
					"type": "User",
					"site_admin": true
				},
				"private": false,
				"html_url": "https://github.com/skalnik/public-repo",
				"description": null,
				"fork": true,
				"url": "https://api.github.com/repos/skalnik/public-repo",
				"created_at": "2016-10-03T23:23:31Z",
				"updated_at": "2016-08-15T17:19:01Z",
				"pushed_at": "2016-10-03T23:36:52Z",
				"git_url": "git://github.com/skalnik/public-repo.git",
				"ssh_url": "git@github.com:skalnik/public-repo.git",
				"clone_url": "https://github.com/skalnik/public-repo.git",
				"svn_url": "https://github.com/skalnik/public-repo",
				"homepage": null,
				"size": 233,
				"stargazers_count": 0,
				"watchers_count": 0,
				"language": null,
				"has_issues": false,
				"has_downloads": true,
				"has_wiki": true,
				"has_pages": false,
				"forks_count": 0,
				"mirror_url": null,
				"open_issues_count": 0,
				"forks": 0,
				"open_issues": 0,
				"watchers": 0,
				"default_branch": "master"
			}
		},
		"base": {
			"label": "baxterthehacker:master",
			"ref": "master",
			"sha": "9049f1265b7d61be4a8904a9a27120d2064dab3b",
			"user": {
				"login": "baxterthehacker",
				"id": 6752317,
				"avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
				"gravatar_id": "",
				"url": "https://api.github.com/users/baxterthehacker",
				"type": "User",
				"site_admin": false
			},
			"repo": {
				"id": 35129377,
				"name": "public-repo",
				"full_name": "baxterthehacker/public-repo",
				"owner": {
					"login": "baxterthehacker",
					"id": 6752317,
					"avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
					"gravatar_id": "",
					"url": "https://api.github.com/users/baxterthehacker",
					"type": "User",
					"site_admin": false
				},
				"private": false,
				"html_url": "https://github.com/baxterthehacker/public-repo",
				"description": "",
				"fork": false,
				"url": "https://api.github.com/repos/baxterthehacker/public-repo",
				"created_at": "2015-05-05T23:40:12Z",
				"updated_at": "2016-08-15T17:19:01Z",
				"pushed_at": "2016-10-03T23:37:43Z",
				"git_url": "git://github.com/baxterthehacker/public-repo.git",
				"ssh_url": "git@github.com:baxterthehacker/public-repo.git",
				"clone_url": "https://github.com/baxterthehacker/public-repo.git",
				"svn_url": "https://github.com/baxterthehacker/public-repo",
				"homepage": null,
				"size": 233,
				"stargazers_count": 2,
				"watchers_count": 2,
				"language": null,
				"has_issues": true,
				"has_downloads": true,
				"has_wiki": true,
				"has_pages": true,
				"forks_count": 2,
				"mirror_url": null,
				"open_issues_count": 5,
				"forks": 2,
				"open_issues": 5,
				"watchers": 2,
				"default_branch": "master"
			}
		},
	},
})
